'language: c
compiler:
  - gcc
os: linux
dist: trusty
before_install:
 - sudo apt-get -qq update
 - cd
 - git clone https://github.com/google/googletest.git
 - which valgrind
 - cd "${TRAVIS_BUILD_DIR}"

before_script:
    - make test
script:
    - ./test
branches:
  only:
    - master
    - student
notifications:
  recipients:
    - jukka.matila@vamk.fi
  email:
    on_success: always
    on_failure: change
rvm:
  - 9.00
